In [1]:
import numpy as np

A1= np.matrix('1')
A2= np.matrix('1 ,2 ,3')
A3= np.matrix('1 ,2 ,3; 4 ,5 ,6; 7 ,8 ,9')
print(A1)
print(A2)
print(A3)

[[1]]
[[1 2 3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


https://prod.liveshare.vsengsaas.visualstudio.com/join?9ECE88F2461DB6DAFF50087D1B445D0434D3

In [2]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a1= np.array([1, 2, 3]) # 1x3  一维的数组 numpy.ndarray
a2= np.array([[1, 2, 3]])  # vector  用二维数组表示一个行向量


print(a1.shape) # (3,)
print(a1.T) # (3,)

print(A@a1) # matrix-vector  矩阵和向量的乘法

(3,)
[1 2 3]
[14 32 50]


In [3]:
import scipy.linalg as la

A = np.mat('1,2,3;4,5,6;7,8,9')
B = np.mat('2,3;4,5')
b= np.mat('-1,-2')
C = np.mat('1,4;2,5;3,6')
d = np.mat('-1;-2;-3')

# basic matrix construction
print(np.identity(4))
print("************")
print(np.eye(4))
print("************")
print(np.zeros((3,3)))
print("************")
print(9* np.ones((3,3)))
print("************")
print(9*np.ones_like(C))





[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
************
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
************
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
************
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
************
[[9 9]
 [9 9]
 [9 9]]


In [25]:
#block diagonal matrix
la.block_diag(A,B,b,C,d)
print(la.block_diag(A,B,b,C,d))


[[ 1  2  3  0  0  0  0  0  0  0]
 [ 4  5  6  0  0  0  0  0  0  0]
 [ 7  8  9  0  0  0  0  0  0  0]
 [ 0  0  0  2  3  0  0  0  0  0]
 [ 0  0  0  4  5  0  0  0  0  0]
 [ 0  0  0  0  0 -1 -2  0  0  0]
 [ 0  0  0  0  0  0  0  1  4  0]
 [ 0  0  0  0  0  0  0  2  5  0]
 [ 0  0  0  0  0  0  0  3  6  0]
 [ 0  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0 -2]
 [ 0  0  0  0  0  0  0  0  0 -3]]


In [4]:
#kron
np.kron(np.identity(5),A)
print(np.kron(np.identity(5),A))


[[1. 2. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 5. 6. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [7. 8. 9. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 2. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 5. 6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 7. 8. 9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 2. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 4. 5. 6. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 7. 8. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 4. 5. 6. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 7. 8. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 4. 5. 6.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 7. 8. 9.]]


In [5]:
np.kron(np.ones((4, 1)),A)
print(np.kron(np.ones((4, 1)),A))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [28]:
#block operation
G4= np.hstack([A,C,C,C,A])
print(G4)

[[1 2 3 1 4 1 4 1 4 1 2 3]
 [4 5 6 2 5 2 5 2 5 4 5 6]
 [7 8 9 3 6 3 6 3 6 7 8 9]]


In [29]:
G6= np.vstack([B,b,b,b,B])
print(G6)

[[ 2  3]
 [ 4  5]
 [-1 -2]
 [-1 -2]
 [-1 -2]
 [ 2  3]
 [ 4  5]]


In [30]:
G = np.block([A,C,C,C])
print(G)

[[1 2 3 1 4 1 4 1 4]
 [4 5 6 2 5 2 5 2 5]
 [7 8 9 3 6 3 6 3 6]]


In [ ]:
# G5=np.block([[A,G6],[np.zeros((3,3)),C]])
# print(G5)

In [ ]:
已经看完了

In [ ]:
11111111

我是没法在这